### ISSUE TITLE
Has this project died?

### ISSUE THREAD

**Issue by pbrubaker** [apache/kibble#14]
There aren't any recent (<9mo) commits to this repository.  Has this project been abandoned?  If so, it's incredibly confusing that all websites refer to this repository and not kibble-1.  You should really fix that until this at least does something.

**Comment by sharanf** [comment]
Hi @pbrubaker. The answer to the question is no - not yet :-). Unfortunately we don't have any active volunteer developers in the community at the moment so this is why there is a lack of commit activity. Thank you for raising a very valid point regarding the confusion caused by the website and the documentation so I'll see what I can do to get this tidied up.

**Comment by ghost** [comment]
> Hi @pbrubaker. The answer to the question is no - not yet :-). Unfortunately we don't have any active volunteer developers in the community at the moment so this is why there is a lack of commit activity. Thank you for raising a very valid point regarding the confusion caused by the website and the documentation so I'll see what I can do to get this tidied up.

Are you people looking for help on development?

**Comment by sharanf** [comment]
Hi @esmiralhaibm Yes we are!. If you are interested then come along and join our mailing list at dev@kibble.apache.org

**Comment by pbrubaker** [comment]
Thanks much @sharanf!
